---
title: "tb missing case sims, dissertation aim 1"
author: "Kristin"
start date: "9/5/2018"
most recent edit: "1/8/2019"
output: html_document
---

```{r, setup and call packages, include=FALSE}
library(GGally)
library(network)
library(sna)
library(statnet)
library(tidyverse)
library(EpiModel)
library(ergm)
library(here)
```


```{r, create networks and target statistics}

##############################################
#INITIATE AN EMPTY NETWORK
##############################################

n_sim <- 2000

nw_sim <- network.initialize(n = n_sim, directed = TRUE)

mean_deg2 <- 2
mean_deg3 <- 3
mean_deg4 <- 4
mean_deg5 <- 5
mean_deg6 <- 6
mean_deg7 <- 7
mean_deg10 <- 10
mean_deg15 <- 15
mean_deg20 <- 20

mds <- matrix(NA, nrow=200, ncol=2)
mds[,1] <- c(1:200)
mds[,2] <- (mds[,1]*n_sim)/2

##############################################
#CREATE AND ASSIGN NODE ATTRIBUTES TO NETWORK
##############################################

# set distribution of node attributes according to distribution in TRAX study 
prophp <- 0.75 #proportion with HP (KZN/LAM4) XDR TB strain

propyr1 <- 0.25 #proportion enrolled into study in each year
propyr2 <- 0.25
propyr3 <- 0.25
propyr4 <- 0.25

propcough <- c(0.37, 0.17, 0.15, 0.21, 0.05, 0.05) # proportion with 1 month, 2 months, 3 months, 4 months, 5 months of cough

#joint distributions of related attributes
prophiv_age <- c(0.01, 0.12, 0.04, 0.05, 0.02, 0.38, 0.35, 0.03)
propsmstat_age <- c(0.01, 0.16, 0.12, 0.03, 0.02, 0.34, 0.27, 0.05)

#assign node attributes to nodes in network
hp <- rbinom(n_sim, 1, prophp)
y_enroll <- sample(1:4, n_sim, replace=TRUE)
cough <- sample(0:5, n_sim, prob=propcough, replace=TRUE) 

#joint distribution of node attributes
hiv_age <- sample(0:7, n_sim, prob=prophiv_age, replace=TRUE) #8 categories (4*2): hiv0_age1, hiv0_age2, hiv0_age3, hiv0_age4, hiv1_age1, hiv1_age2, hiv1_age3, hiv1_age4)

smstat_age <- sample(0:7, n_sim, prob=propsmstat_age, replace=TRUE) #8 categories (4*2): sm0_age1, sm0_age2, sm0_age3, sm0_age4, sm1_age1, sm1_age2, sm1_age3, sm1_age4)

nw_sim <- set.vertex.attribute(nw_sim, attrname = "hp", value = hp)
nw_sim <- set.vertex.attribute(nw_sim, attrname = "yr", value = y_enroll)
nw_sim <- set.vertex.attribute(nw_sim, attrname = "cough", value = cough)
nw_sim <- set.vertex.attribute(nw_sim, attrname = "hiv_age", value = hiv_age)
nw_sim <- set.vertex.attribute(nw_sim, attrname = "smstat_age", value = smstat_age)

#Specify vertex attributes for UNDIRECTED networks

nw_sim_un <- network.initialize(n = n_sim, directed = FALSE)

nw_sim_un <- set.vertex.attribute(nw_sim_un, attrname = "hp", value = hp)
nw_sim_un <- set.vertex.attribute(nw_sim_un, attrname = "yr", value = y_enroll)
nw_sim_un <- set.vertex.attribute(nw_sim_un, attrname = "cough", value = cough)
nw_sim_un <- set.vertex.attribute(nw_sim_un, attrname = "hiv_age", value = hiv_age)
nw_sim_un <- set.vertex.attribute(nw_sim_un, attrname = "smstat_age", value = smstat_age)

##############################################
#CREATE TARGET STATISTICS FOR SIMULATED NETWORKS
##############################################

#define relative outedges target stats for outedges based on observed network (dnet_le5_pMDR_dxdiff_gt60)
mn.2011 <- 8    #mean edges (links) per case enrolled in 2011
mn.2012 <- 5.6  #mean edges per case enrolled in 2012
mn.2013 <- 5.8  #mean edges per case enrolled in 2013
mn.2014 <- 6.4  #mean edges per case enrolled in 2014

mn.hp <- 8.3    #mean edges (links) per case with HP strain
mn.nonhp <- 0.2 #mean edges (links) per case with HP strain

md.trax.le5 <- 6.3 #overall mean degree in empirical TRAX network (with SNP threshold of le5)

md <- c(2:7, 10, 15, 20, 25, 30, 40, 50) #calculate target statistics for networks with different mean degrees

##target stats for hp
##hp
mn.hp.rel <- mn.hp/md.trax.le5 #relative mean degree in trax (empiric) network
mn.nonhp.rel <- mn.nonhp/md.trax.le5 #relative mean degree in trax (empiric) network

hp_nfstats_all <- list()

for(i in(1:200)){
  
md.hp <- mn.hp.rel*i
md.nonhp <- (i - (md.hp * prophp))/(1-prophp)

assign((paste0("edges.hp.md", i)), (md.hp * sum(hp == 1)))
assign(paste0("edges.nonhp.md", i), md.nonhp * sum(hp == 0))

hp_nfstats <- numeric(2)
hp_nfstats[1] <- md.hp * sum(hp == 1)
hp_nfstats[2] <- md.nonhp * sum(hp == 0)

hp_nfstats_all[[i]] <- hp_nfstats
}

#check that hp + nonhp edges add up to total
#(edges.hp.md2 + edges.nonhp.md2)/2 
#edges_sim_md2

##target stats for year
mn.2011.rel <- mn.2011/md.trax.le5
mn.2012.rel <- mn.2012/md.trax.le5
mn.2013.rel <- mn.2013/md.trax.le5
mn.2014.rel <- mn.2014/md.trax.le5

yr_nfstats_all <- list()

for(i in(1:200)){
  
md.2011 <- mn.2011.rel*i
md.2012 <- mn.2012.rel*i
md.2013 <- mn.2013.rel*i
md.2014 <- ((i - ((md.2011*propyr1) + (md.2012*propyr2) + (md.2013*propyr3))) / (1-(propyr1 + propyr2 + propyr3)))

assign(paste0("edges.2011.md", i), md.2011 * sum(y_enroll == 1))
assign(paste0("edges.2012.md", i), md.2012 * sum(y_enroll == 2))
assign(paste0("edges.2013.md", i), md.2013 * sum(y_enroll == 3))
assign(paste0("edges.2014.md", i), md.2014 * sum(y_enroll == 4))

yr_nfstats <- numeric(4)
yr_nfstats[1] <- md.2011 * sum(y_enroll == 1)
yr_nfstats[2] <- md.2012 * sum(y_enroll == 2)
yr_nfstats[3] <- md.2013 * sum(y_enroll == 3)
yr_nfstats[4] <- md.2014 * sum(y_enroll == 4)

yr_nfstats_all[[i]] <- yr_nfstats
}

##cough
mn.cough0 <- 5.0
mn.cough1 <- 6.5
mn.cough2 <- 8.1
mn.cough3 <- 8.1
mn.cough4 <- 4.6
mn.cough5 <- 3.7
 
#normalized joint distributions - LITERATURE (SMEAR, AGE)
mn.hivneg_agecat15  <- 1 * 1  * md.trax.le5
mn.hivneg_agecat1634  <- 1 * 1.58 * md.trax.le5
mn.hivneg_agecat3554  <- 1 * 0.98 * md.trax.le5
mn.hivneg_agecat55  <- 1 * 0.75 * md.trax.le5
mn.hivpos_agecat15  <- 1 * 1 * md.trax.le5
mn.hivpos_agecat1634  <- 1 * 1.58 * md.trax.le5
mn.hivpos_agecat3554  <- 1 * 0.98 * md.trax.le5
mn.hivpos_agecat55  <- 1 * 0.75 * md.trax.le5

mn.smneg_agecat15  <- 0.25 * 1 * md.trax.le5
mn.smneg_agecat1634  <- 0.25 * 1.58 * md.trax.le5
mn.smneg_agecat3554  <- 0.25 * 0.98 * md.trax.le5
mn.smneg_agecat55  <- 0.25 * 0.75 * md.trax.le5
mn.smpos_agecat15  <- 1 * 1 * md.trax.le5
mn.smpos_agecat1634  <- 1 * 1.58 * md.trax.le5
mn.smpos_agecat3554  <- 1 * 0.98 * md.trax.le5 
mn.smpos_agecat55  <- 1 * 0.75 * md.trax.le5
# Abu-Raddad et al. PNAS 2009 (smear)
# Wood et al. Plos One 2012 (age)

##target stats for hiv and age joint distrbution (hiv_age)
mn.hivneg_agecat15.rel <- mn.hivneg_agecat15/md.trax.le5
mn.hivneg_agecat1634.rel <- mn.hivneg_agecat1634/md.trax.le5
mn.hivneg_agecat3554.rel <- mn.hivneg_agecat3554/md.trax.le5
mn.hivneg_agecat55.rel <- mn.hivneg_agecat55/md.trax.le5

mn.hivpos_agecat15.rel <- mn.hivpos_agecat15/md.trax.le5
mn.hivpos_agecat1634.rel <- mn.hivpos_agecat1634/md.trax.le5
mn.hivpos_agecat3554.rel <- mn.hivpos_agecat3554/md.trax.le5
mn.hivpos_agecat55.rel <- mn.hivpos_agecat55/md.trax.le5

hivage_nfstats_all <- list()

for(i in(1:200)){
  
md.hivneg_agecat15 <- mn.hivneg_agecat15.rel*i
md.hivneg_agecat1634 <- mn.hivneg_agecat1634.rel*i
md.hivneg_agecat3554 <- mn.hivneg_agecat3554.rel*i
md.hivneg_agecat55 <- mn.hivneg_agecat55.rel*i
md.hivpos_agecat15 <- mn.hivpos_agecat15.rel*i
md.hivpos_agecat1634 <- mn.hivpos_agecat1634.rel*i
md.hivpos_agecat3554 <- mn.hivpos_agecat3554.rel*i
md.hivpos_agecat55 <- ((i - ((md.hivneg_agecat15*prophiv_age[1]) + 
                             (md.hivneg_agecat1634*prophiv_age[2]) + 
                             (md.hivneg_agecat3554*prophiv_age[3]) +
                             (md.hivneg_agecat55*prophiv_age[4]) +
                             (md.hivpos_agecat15*prophiv_age[5]) +
                             (md.hivpos_agecat1634*prophiv_age[6]) +
                             (md.hivpos_agecat3554*prophiv_age[7]))) / 
                             (1 - sum(prophiv_age[1:7])))

assign(paste0("edges.hiv_age0.md", i), md.hivneg_agecat15 * sum(hiv_age == 0))
assign(paste0("edges.hiv_age1.md", i), md.hivneg_agecat1634 * sum(hiv_age == 1))
assign(paste0("edges.hiv_age2.md", i), md.hivneg_agecat3554 * sum(hiv_age == 2))
assign(paste0("edges.hiv_age3.md", i), md.hivneg_agecat55 * sum(hiv_age == 3))
assign(paste0("edges.hiv_age4.md", i), md.hivpos_agecat15 * sum(hiv_age == 4))
assign(paste0("edges.hiv_age5.md", i), md.hivpos_agecat1634 * sum(hiv_age == 5))
assign(paste0("edges.hiv_age6.md", i), md.hivpos_agecat3554 * sum(hiv_age == 6))
assign(paste0("edges.hiv_age7.md", i), md.hivpos_agecat55 * sum(hiv_age == 7))
  
hivage_nfstats <- numeric(8)
hivage_nfstats[1] <- md.hivneg_agecat15 * sum(hiv_age== 0)
hivage_nfstats[2] <- md.hivneg_agecat1634 * sum(hiv_age== 1)
hivage_nfstats[3] <- md.hivneg_agecat3554 * sum(hiv_age== 2)
hivage_nfstats[4] <- md.hivneg_agecat55 * sum(hiv_age== 3)
hivage_nfstats[5] <- md.hivpos_agecat15 * sum(hiv_age== 4)
hivage_nfstats[6] <- md.hivpos_agecat1634 * sum(hiv_age== 5)
hivage_nfstats[7] <- md.hivpos_agecat3554 * sum(hiv_age== 6)
hivage_nfstats[8] <- md.hivpos_agecat55 * sum(hiv_age == 7)
  
hivage_nfstats_all[[i]] <- hivage_nfstats
}

##target stats for smear status and age joint distribution (smstat_age)
mn.smneg_agecat15.rel <- mn.smneg_agecat15/md.trax.le5
mn.smneg_agecat1634.rel <- mn.smneg_agecat1634/md.trax.le5
mn.smneg_agecat3554.rel <- mn.smneg_agecat3554/md.trax.le5
mn.smneg_agecat55.rel <- mn.smneg_agecat55/md.trax.le5
mn.smpos_agecat15.rel <- mn.smpos_agecat15/md.trax.le5
mn.smpos_agecat1634.rel <- mn.smpos_agecat1634/md.trax.le5
mn.smpos_agecat3554.rel <- mn.smpos_agecat3554/md.trax.le5
mn.smpos_agecat55.rel <- mn.smpos_agecat55/md.trax.le5

smage_nfstats_all <- list()

for(i in(1:200)){
  
md.smneg_agecat15 <- mn.smneg_agecat15.rel*i
md.smneg_agecat1634 <- mn.smneg_agecat1634.rel*i
md.smneg_agecat3554 <- mn.smneg_agecat3554.rel*i
md.smneg_agecat55 <- mn.smneg_agecat55.rel*i
md.smpos_agecat15 <- mn.smpos_agecat15.rel*i
md.smpos_agecat1634 <- mn.smpos_agecat1634.rel*i
md.smpos_agecat3554 <- mn.smpos_agecat3554.rel*i
md.smpos_agecat55 <- ((i - ((md.smneg_agecat15*propsmstat_age[1]) + 
                             (md.smneg_agecat1634*propsmstat_age[2]) + 
                             (md.smneg_agecat3554*propsmstat_age[3]) +
                             (md.smneg_agecat55*propsmstat_age[4]) +
                             (md.smpos_agecat15*propsmstat_age[5]) +
                             (md.smpos_agecat1634*propsmstat_age[6]) +
                             (md.smpos_agecat3554*propsmstat_age[7]))) / 
                             (1 - sum(propsmstat_age[1:7])))

assign(paste0("edges.sm_age0.md", i), md.smneg_agecat15 * sum(smstat_age== 0))
assign(paste0("edges.sm_age1.md", i), md.smneg_agecat1634 * sum(smstat_age== 1))
assign(paste0("edges.sm_age2.md", i), md.smneg_agecat3554 * sum(smstat_age== 2))
assign(paste0("edges.sm_age3.md", i), md.smneg_agecat55 * sum(smstat_age== 3))
assign(paste0("edges.sm_age4.md", i), md.smpos_agecat15 * sum(smstat_age== 4))
assign(paste0("edges.sm_age5.md", i), md.smpos_agecat1634 * sum(smstat_age== 5))
assign(paste0("edges.sm_age6.md", i), md.smpos_agecat3554 * sum(smstat_age== 6))
assign(paste0("edges.sm_age7.md", i), md.smpos_agecat55 * sum(smstat_age == 7))

smage_nfstats <- numeric(8)
smage_nfstats[1] <- md.smneg_agecat15 * sum(smstat_age== 0)
smage_nfstats[2] <- md.smneg_agecat1634 * sum(smstat_age== 1)
smage_nfstats[3] <- md.smneg_agecat3554 * sum(smstat_age== 2)
smage_nfstats[4] <- md.smneg_agecat55 * sum(smstat_age== 3)
smage_nfstats[5] <- md.smpos_agecat15 * sum(smstat_age== 4)
smage_nfstats[6] <- md.smpos_agecat1634 * sum(smstat_age== 5)
smage_nfstats[7] <- md.smpos_agecat3554 * sum(smstat_age== 6)
smage_nfstats[8] <- md.smpos_agecat55 * sum(smstat_age == 7)
  
smage_nfstats_all[[i]] <- smage_nfstats
}

##target stats for cough
mn.cough0.rel <- mn.cough0/md.trax.le5
mn.cough1.rel <- mn.cough1/md.trax.le5
mn.cough2.rel <- mn.cough2/md.trax.le5
mn.cough3.rel <- mn.cough3/md.trax.le5
mn.cough4.rel <- mn.cough4/md.trax.le5
mn.cough5.rel <- mn.cough5/md.trax.le5

cough_nfstats_all <- list()

for(i in(1:200)){
  
md.cough0 <- mn.cough0.rel*i
md.cough1 <- mn.cough1.rel*i
md.cough2 <- mn.cough2.rel*i
md.cough3 <- mn.cough3.rel*i
md.cough4 <- mn.cough4.rel*i
md.cough5 <- ((i - ((md.cough0*propcough[1]) + 
                             (md.cough1*propcough[2]) + 
                             (md.cough2*propcough[3]) +
                             (md.cough3*propcough[4]) +
                             (md.cough4*propcough[5]))) / 
                             (1-sum(propcough[1:5])))

assign(paste0("edges.cough0.md", i), md.cough0 * sum(cough== 0))
assign(paste0("edges.cough1.md", i), md.cough1 * sum(cough== 1))
assign(paste0("edges.cough2.md", i), md.cough2 * sum(cough== 2))
assign(paste0("edges.cough3.md", i), md.cough3 * sum(cough== 3))
assign(paste0("edges.cough4.md", i), md.cough4 * sum(cough== 4))
assign(paste0("edges.cough5.md", i), md.cough5 * sum(cough== 5))

cough_nfstats <- numeric(6)
cough_nfstats[1] <- md.cough0 * sum(cough== 0)
cough_nfstats[2] <- md.cough1 * sum(cough== 1)
cough_nfstats[3] <- md.cough2 * sum(cough== 2)
cough_nfstats[4]<- md.cough3 * sum(cough== 3)
cough_nfstats[5]<- md.cough4 * sum(cough== 4)
cough_nfstats[6] <- md.cough5 * sum(cough== 5)

cough_nfstats_all[[i]] <- cough_nfstats

}
#combine all vars into a dataframe
#columns are cough categories (0-5), rows are mean degrees. 
#e.g. for md2 models, want cough_nfstats_mat[x,1] where x is cough category
edges_nfstats <- mds
hp_nfstats_mat <- matrix(unlist(hp_nfstats_all), nrow=200, ncol=2, byrow=TRUE)
yr_nfstats_mat <- matrix(unlist(yr_nfstats_all), nrow=200, ncol=4, byrow=TRUE)
cough_nfstats_mat <- matrix(unlist(cough_nfstats_all), nrow=200, ncol=6, byrow=TRUE)
smage_nfstats_mat <- matrix(unlist(smage_nfstats_all), nrow=200, ncol=8, byrow=TRUE)
hivage_nfstats_mat <- matrix(unlist(hivage_nfstats_all), nrow=200, ncol=8, byrow=TRUE)

```

```{r, ergms}

##############################################
#RUN ERGMS at DIFFERENT MEAN DEGREES, using edge target stats
##############################################

nw_md <- list()

for(i in(c(2, 5, 8, 10, 15, 20, 100, 150, 200))){
  
nw <- ergm(nw_sim_un ~ edges + nodefactor("hp", base = 1) + nodefactor("yr", base = 1) + nodefactor("cough", base = 5:6) + nodefactor("smstat_age", base = c(1, 4:5, 8)) + nodefactor("hiv_age", base = c(1:5, 8)), control = control.ergm(MCMC.burnin = 100000, MCMC.samplesize=10000, MCMLE.maxit = 100, MCMC.interval = 5000, MCMLE.density.guard = exp(10)),
                                    target.stats = c(edges_nfstats[i,2], 
                                          hp_nfstats_mat[i,1], 
                                          yr_nfstats_mat[i,2], yr_nfstats_mat[i,3], yr_nfstats_mat[i,4],
                                          cough_nfstats_mat[i,1], cough_nfstats_mat[i,2], cough_nfstats_mat[i,3], cough_nfstats_mat[i,4], 
                                          smage_nfstats_mat[i,2], smage_nfstats_mat[i,3], smage_nfstats_mat[i,6], smage_nfstats_mat[i,7],
                                          hivage_nfstats_mat[i,6], hivage_nfstats_mat[i,7]))

nw_md[[i]] <- nw

saveRDS(nw, file = paste("nw_", n_sim, "_md",i,".RDS"))

}

nw_md <- list()
nw_md[[2]] <- readRDS("nw_2000_md2.RDS")
nw_md[[5]] <- readRDS("nw_2000_md5.RDS")
nw_md[[10]] <- readRDS("nw_2000_md10.RDS")
nw_md[[15]] <- readRDS("nw_2000_md15.RDS")
nw_md[[20]] <- readRDS("nw_2000_md20.RDS")
nw_md[[50]] <- readRDS("nw_2000_md50.RDS")
nw_md[[100]] <- readRDS("nw_2000_md100.RDS")
nw_md[[200]] <- readRDS("nw_2000_md200.RDS")

##############################################
#SAMPLE FROM SIMULATED, FULL NETWORKS (random and nonrandom sampling)
##############################################


ransamp <- sample(network.size(nw_sim_un), 350, replace = FALSE, prob = NULL)
nsamples <- 1000

#random sample (n = 350) of each simulated network.
for(k in(c(2, 5, 8, 10, 15, 20, 100, 150, 200))){
  
        degdist <- list()
      
        med <- list()
        
for(i in 1:nsamples){
    
      nw_sim <- simulate(nw_md[[k]], nsim = 1, monitor = ~ degree(0:100) + meandeg)
      
      degtosamp <- degree(nw_sim, gmode = "graph" , cmode="freeman", ignore.eval = TRUE)
      
      degtable <- as.data.frame(cbind(degtosamp, 1:n_sim))
      
      nonransamp <- sample_n(degtable, 350, replace = FALSE)
      
      nonransamp <- nonransamp[,2]
    
      sim_deg <- degree(get.inducedSubgraph(nw_sim, nonransamp), gmode = "graph" , cmode="freeman", ignore.eval = TRUE)
      
      simdegdist <- table(sim_deg) 
      
      degdist[[i]] <- as.data.frame(simdegdist) #keep degree distribution of each sampled network
      
      quantiles <- quantile(sim_deg, c(0.25, 0.50, 0.75, 1)) #gives median degree and IQR for each network
      
      med[[i]] <- as.vector(quantiles)
      
      #delete simulated nw
      rm(nw_sim)
      
    } 
      saveRDS(degdist, file = paste("nw", n_sim, "sim", nsamples, "nonran_deg_md", k, "degdist.RDS", sep = "_"))
      saveRDS(med, file = paste("nw", n_sim, "sim", nsamples, "nonran_deg_md", k, "med.RDS", sep = "_"))
}

#non-random sample (n = 350, sample weight is inverse degree) of each simulated network.
for(k in(c(2, 5, 8, 10, 15, 20, 100, 150, 200))){
  
        degdist <- list()
      
        med <- list()
        
for(i in 1:nsamples){
    
      nw_sim <- simulate(nw_md[[k]], nsim = 1, monitor = ~ degree(0:100) + meandeg)
      
      degtosamp <- degree(nw_sim, gmode = "graph" , cmode="freeman", ignore.eval = TRUE)
      
      degtable <- as.data.frame(cbind(degtosamp, 1:n_sim))
      
      nonransamp <- sample_n(degtable, 350, replace = FALSE, weight = degtosamp + 0.1)
      
      nonransamp <- nonransamp[,2]
    
      sim_deg <- degree(get.inducedSubgraph(nw_sim, nonransamp), gmode = "graph" , cmode="freeman", ignore.eval = TRUE)
      
      simdegdist <- table(sim_deg) 
      
      degdist[[i]] <- as.data.frame(simdegdist)  #keep degree distribution of each sampled network
      
      quantiles <- quantile(sim_deg, c(0.25, 0.50, 0.75, 1)) #gives median degree and IQR for each network
      
      med[[i]] <- as.vector(quantiles)
      
      #delete simulated nw
      rm(nw_sim)
      
    } 
      saveRDS(degdist, file = paste("nw", n_sim, "sim", nsamples, "nonran_deg_md", k, "degdist.RDS", sep = "_"))
      saveRDS(med, file = paste("nw", n_sim, "sim", nsamples, "nonran_deg_md", k, "med.RDS", sep = "_"))
}

```

```{r, changing attribute distribution}

##############################################
#CREATE FULL NETWORKS WITH DIFF. DIST'NS OF HIV/SMEAR STATUS
##############################################

#create new networks that will have different *hiv status* distribution
nw_sim_un_b1 <- network.initialize(n = n_sim, directed = FALSE)
nw_sim_un_b2 <- network.initialize(n = n_sim, directed = FALSE)
nw_sim_un_b3 <- network.initialize(n = n_sim, directed = FALSE)
nw_sim_un_b4 <- network.initialize(n = n_sim, directed = FALSE)

#create new networks that will have different *smear status* distribution
nw_sim_un_c1 <- network.initialize(n = n_sim, directed = FALSE)
nw_sim_un_c2 <- network.initialize(n = n_sim, directed = FALSE)
nw_sim_un_c3 <- network.initialize(n = n_sim, directed = FALSE)
nw_sim_un_c4 <- network.initialize(n = n_sim, directed = FALSE)

#60/40 HIV-/+
hiv_age_b1 <- sample(0:7, n_sim, prob=c((0.6*0.03), (0.6*0.5), (0.6*0.39), (0.6*0.08), (0.4*0.03), (0.4*0.5), (0.4*0.39), (0.4*0.08)), replace=TRUE) #8 categories (4*2): hiv0_age1, hiv0_age2, hiv0_age3, hiv0_age4, hiv1_age1, hiv1_age2, hiv1_age3, hiv1_age4)
#10/90 HIV-/+
hiv_age_b2 <- sample(0:7, n_sim, prob=c((0.1*0.03), (0.1*0.5), (0.1*0.39), (0.1*0.08), (0.9*0.03), (0.9*0.5), (0.9*0.39), (0.9*0.08)), replace=TRUE)  
#50/50 HIV-/+
hiv_age_b3 <- sample(0:7, n_sim, prob=c((0.5*0.03), (0.5*0.5), (0.5*0.39), (0.5*0.08), (0.5*0.03), (0.5*0.5), (0.5*0.39), (0.5*0.08)), replace=TRUE)  
#70/30 HIV-/+
hiv_age_b4 <- sample(0:7, n_sim, prob=c((0.7*0.03), (0.7*0.5), (0.7*0.39), (0.7*0.08), (0.3*0.03), (0.3*0.5), (0.3*0.39), (0.3*0.08)), replace=TRUE)  

# 50/50 smear-/+
sm_age_c1 <- sample(0:7, n_sim, prob=c((0.5*0.03), (0.5*0.5), (0.5*0.39), (0.5*0.08), (0.5*0.03), (0.5*0.5), (0.5*0.39), (0.5*0.08)), replace=TRUE) #8 categories (4*2): sm0_age1, sm0_age2, sm0_age3, sm0_age4, sm1_age1, sm1_age2, sm1_age3, sm1_age4)
# 70/30 smear-/+
sm_age_c2 <- sample(0:7, n_sim, prob=c((0.7*0.03), (0.7*0.5), (0.7*0.39), (0.7*0.08), (0.3*0.03), (0.3*0.5), (0.3*0.39), (0.3*0.08)), replace=TRUE)
# 90/10 smear-/+
sm_age_c3 <- sample(0:7, n_sim, prob=c((0.9*0.03), (0.9*0.5), (0.9*0.39), (0.9*0.08), (0.1*0.03), (0.1*0.5), (0.1*0.39), (0.1*0.08)), replace=TRUE)
# 30/70 smear-/+
sm_age_c4 <- sample(0:7, n_sim, prob=c((0.3*0.03), (0.3*0.5), (0.3*0.39), (0.3*0.08), (0.7*0.03), (0.7*0.5), (0.7*0.39), (0.7*0.08)), replace=TRUE)

#assign new distributions to networks
nw_sim_un_b1 <- set.vertex.attribute(nw_sim_un_b1, attrname = "hp", value = hp)
nw_sim_un_b1 <- set.vertex.attribute(nw_sim_un_b1, attrname = "yr", value = y_enroll)
nw_sim_un_b1 <- set.vertex.attribute(nw_sim_un_b1, attrname = "cough", value = cough)
nw_sim_un_b1 <- set.vertex.attribute(nw_sim_un_b1, attrname = "hiv_age_b1", value = hiv_age_b1)
nw_sim_un_b1 <- set.vertex.attribute(nw_sim_un_b1, attrname = "smstat_age", value = smstat_age)

nw_sim_un_b2 <- set.vertex.attribute(nw_sim_un_b2, attrname = "hp", value = hp)
nw_sim_un_b2 <- set.vertex.attribute(nw_sim_un_b2, attrname = "yr", value = y_enroll)
nw_sim_un_b2 <- set.vertex.attribute(nw_sim_un_b2, attrname = "cough", value = cough)
nw_sim_un_b2 <- set.vertex.attribute(nw_sim_un_b2, attrname = "hiv_age_b2", value = hiv_age_b2)
nw_sim_un_b2 <- set.vertex.attribute(nw_sim_un_b2, attrname = "smstat_age", value = smstat_age)

nw_sim_un_b3 <- set.vertex.attribute(nw_sim_un_b3, attrname = "hp", value = hp)
nw_sim_un_b3 <- set.vertex.attribute(nw_sim_un_b3, attrname = "yr", value = y_enroll)
nw_sim_un_b3 <- set.vertex.attribute(nw_sim_un_b3, attrname = "cough", value = cough)
nw_sim_un_b3 <- set.vertex.attribute(nw_sim_un_b3, attrname = "hiv_age_b3", value = hiv_age_b3)
nw_sim_un_b3 <- set.vertex.attribute(nw_sim_un_b3, attrname = "smstat_age", value = smstat_age)

nw_sim_un_b4 <- set.vertex.attribute(nw_sim_un_b4, attrname = "hp", value = hp)
nw_sim_un_b4 <- set.vertex.attribute(nw_sim_un_b4, attrname = "yr", value = y_enroll)
nw_sim_un_b4 <- set.vertex.attribute(nw_sim_un_b4, attrname = "cough", value = cough)
nw_sim_un_b4 <- set.vertex.attribute(nw_sim_un_b4, attrname = "hiv_age_b4", value = hiv_age_b4)
nw_sim_un_b4 <- set.vertex.attribute(nw_sim_un_b4, attrname = "smstat_age", value = smstat_age)

nw_sim_un_c1 <- set.vertex.attribute(nw_sim_un_c1, attrname = "hp", value = hp)
nw_sim_un_c1 <- set.vertex.attribute(nw_sim_un_c1, attrname = "yr", value = y_enroll)
nw_sim_un_c1 <- set.vertex.attribute(nw_sim_un_c1, attrname = "cough", value = cough)
nw_sim_un_c1 <- set.vertex.attribute(nw_sim_un_c1, attrname = "hiv_age", value = hiv_age)
nw_sim_un_c1 <- set.vertex.attribute(nw_sim_un_c1, attrname = "smstat_age_c1", value = sm_age_c1)

nw_sim_un_c2 <- set.vertex.attribute(nw_sim_un_c2, attrname = "hp", value = hp)
nw_sim_un_c2 <- set.vertex.attribute(nw_sim_un_c2, attrname = "yr", value = y_enroll)
nw_sim_un_c2 <- set.vertex.attribute(nw_sim_un_c2, attrname = "cough", value = cough)
nw_sim_un_c2 <- set.vertex.attribute(nw_sim_un_c2, attrname = "hiv_age", value = hiv_age)
nw_sim_un_c2 <- set.vertex.attribute(nw_sim_un_c2, attrname = "smstat_age_c2", value = sm_age_c2)

nw_sim_un_c3 <- set.vertex.attribute(nw_sim_un_c3, attrname = "hp", value = hp)
nw_sim_un_c3 <- set.vertex.attribute(nw_sim_un_c3, attrname = "yr", value = y_enroll)
nw_sim_un_c3 <- set.vertex.attribute(nw_sim_un_c3, attrname = "cough", value = cough)
nw_sim_un_c3 <- set.vertex.attribute(nw_sim_un_c3, attrname = "hiv_age", value = hiv_age)
nw_sim_un_c3 <- set.vertex.attribute(nw_sim_un_c3, attrname = "smstat_age_c3", value = sm_age_c3)

nw_sim_un_c4 <- set.vertex.attribute(nw_sim_un_c4, attrname = "hp", value = hp)
nw_sim_un_c4 <- set.vertex.attribute(nw_sim_un_c4, attrname = "yr", value = y_enroll)
nw_sim_un_c4 <- set.vertex.attribute(nw_sim_un_c4, attrname = "cough", value = cough)
nw_sim_un_c4 <- set.vertex.attribute(nw_sim_un_c4, attrname = "hiv_age", value = hiv_age)
nw_sim_un_c4 <- set.vertex.attribute(nw_sim_un_c4, attrname = "smstat_age_c4", value = sm_age_c4)

##############################################
#CREATE TARGET STATS AT DIFF. MEAN DEGREES FOR THESE NEW NETWORKS
##############################################

##hiv_age_b1/b2/b3/b4
hivage_nfstats_all_b1 <- list()

for(i in(1:20)){
  
md.hivneg_agecat15 <- mn.hivneg_agecat15.rel*i
md.hivneg_agecat1634 <- mn.hivneg_agecat1634.rel*i
md.hivneg_agecat3554 <- mn.hivneg_agecat3554.rel*i
md.hivneg_agecat55 <- mn.hivneg_agecat55.rel*i
md.hivpos_agecat15 <- mn.hivpos_agecat15.rel*i
md.hivpos_agecat1634 <- mn.hivpos_agecat1634.rel*i
md.hivpos_agecat3554 <- mn.hivpos_agecat3554.rel*i
md.hivpos_agecat55 <- ((i - ((md.hivneg_agecat15*hiv_age_b1[1]) + 
                             (md.hivneg_agecat1634*hiv_age_b1[2]) + 
                             (md.hivneg_agecat3554*hiv_age_b1[3]) +
                             (md.hivneg_agecat55*hiv_age_b1[4]) +
                             (md.hivpos_agecat15*hiv_age_b1[5]) +
                             (md.hivpos_agecat1634*hiv_age_b1[6]) +
                             (md.hivpos_agecat3554*hiv_age_b1[7]))) / 
                             (1 - sum(hiv_age_b1[1:7])))

assign(paste0("edges.hiv_age0_b1.md", i), md.hivneg_agecat15 * sum(hiv_age_b1 == 0))
assign(paste0("edges.hiv_age1_b1.md", i), md.hivneg_agecat1634 * sum(hiv_age_b1 == 1))
assign(paste0("edges.hiv_age2_b1.md", i), md.hivneg_agecat3554 * sum(hiv_age_b1 == 2))
assign(paste0("edges.hiv_age3_b1.md", i), md.hivneg_agecat55 * sum(hiv_age_b1 == 3))
assign(paste0("edges.hiv_age4_b1.md", i), md.hivpos_agecat15 * sum(hiv_age_b1 == 4))
assign(paste0("edges.hiv_age5_b1.md", i), md.hivpos_agecat1634 * sum(hiv_age_b1 == 5))
assign(paste0("edges.hiv_age6_b1.md", i), md.hivpos_agecat3554 * sum(hiv_age_b1 == 6))
assign(paste0("edges.hiv_age7_b1.md", i), md.hivpos_agecat55 * sum(hiv_age_b1 == 7))
  
hivage_nfstats <- numeric(8)
hivage_nfstats[1] <- md.hivneg_agecat15 * sum(hiv_age_b1== 0)
hivage_nfstats[2] <- md.hivneg_agecat1634 * sum(hiv_age_b1== 1)
hivage_nfstats[3] <- md.hivneg_agecat3554 * sum(hiv_age_b1== 2)
hivage_nfstats[4] <- md.hivneg_agecat55 * sum(hiv_age_b1== 3)
hivage_nfstats[5] <- md.hivpos_agecat15 * sum(hiv_age_b1== 4)
hivage_nfstats[6] <- md.hivpos_agecat1634 * sum(hiv_age_b1== 5)
hivage_nfstats[7] <- md.hivpos_agecat3554 * sum(hiv_age_b1== 6)
hivage_nfstats[8] <- md.hivpos_agecat55 * sum(hiv_age_b1 == 7)
  
hivage_nfstats_all_b1[[i]] <- hivage_nfstats
}

hivage_nfstats_all_b2 <- list()

for(i in(1:20)){
  
md.hivneg_agecat15 <- mn.hivneg_agecat15.rel*i
md.hivneg_agecat1634 <- mn.hivneg_agecat1634.rel*i
md.hivneg_agecat3554 <- mn.hivneg_agecat3554.rel*i
md.hivneg_agecat55 <- mn.hivneg_agecat55.rel*i
md.hivpos_agecat15 <- mn.hivpos_agecat15.rel*i
md.hivpos_agecat1634 <- mn.hivpos_agecat1634.rel*i
md.hivpos_agecat3554 <- mn.hivpos_agecat3554.rel*i
md.hivpos_agecat55 <- ((i - ((md.hivneg_agecat15*hiv_age_b2[1]) + 
                             (md.hivneg_agecat1634*hiv_age_b2[2]) + 
                             (md.hivneg_agecat3554*hiv_age_b2[3]) +
                             (md.hivneg_agecat55*hiv_age_b2[4]) +
                             (md.hivpos_agecat15*hiv_age_b2[5]) +
                             (md.hivpos_agecat1634*hiv_age_b2[6]) +
                             (md.hivpos_agecat3554*hiv_age_b2[7]))) / 
                             (1 - sum(hiv_age_b2[1:7])))

assign(paste0("edges.hiv_age0_b2.md", i), md.hivneg_agecat15 * sum(hiv_age_b2 == 0))
assign(paste0("edges.hiv_age1_b2.md", i), md.hivneg_agecat1634 * sum(hiv_age_b2 == 1))
assign(paste0("edges.hiv_age2_b2.md", i), md.hivneg_agecat3554 * sum(hiv_age_b2 == 2))
assign(paste0("edges.hiv_age3_b2.md", i), md.hivneg_agecat55 * sum(hiv_age_b2 == 3))
assign(paste0("edges.hiv_age4_b2.md", i), md.hivpos_agecat15 * sum(hiv_age_b2 == 4))
assign(paste0("edges.hiv_age5_b2.md", i), md.hivpos_agecat1634 * sum(hiv_age_b2 == 5))
assign(paste0("edges.hiv_age6_b2.md", i), md.hivpos_agecat3554 * sum(hiv_age_b2 == 6))
assign(paste0("edges.hiv_age7_b2.md", i), md.hivpos_agecat55 * sum(hiv_age_b2 == 7))
  
hivage_nfstats <- numeric(8)
hivage_nfstats[1] <- md.hivneg_agecat15 * sum(hiv_age_b2== 0)
hivage_nfstats[2] <- md.hivneg_agecat1634 * sum(hiv_age_b2== 1)
hivage_nfstats[3] <- md.hivneg_agecat3554 * sum(hiv_age_b2== 2)
hivage_nfstats[4] <- md.hivneg_agecat55 * sum(hiv_age_b2== 3)
hivage_nfstats[5] <- md.hivpos_agecat15 * sum(hiv_age_b2== 4)
hivage_nfstats[6] <- md.hivpos_agecat1634 * sum(hiv_age_b2== 5)
hivage_nfstats[7] <- md.hivpos_agecat3554 * sum(hiv_age_b2== 6)
hivage_nfstats[8] <- md.hivpos_agecat55 * sum(hiv_age_b2 == 7)
  
hivage_nfstats_all_b2[[i]] <- hivage_nfstats
}

hivage_nfstats_all_b3 <- list()

for(i in(1:20)){
  
md.hivneg_agecat15 <- mn.hivneg_agecat15.rel*i
md.hivneg_agecat1634 <- mn.hivneg_agecat1634.rel*i
md.hivneg_agecat3554 <- mn.hivneg_agecat3554.rel*i
md.hivneg_agecat55 <- mn.hivneg_agecat55.rel*i
md.hivpos_agecat15 <- mn.hivpos_agecat15.rel*i
md.hivpos_agecat1634 <- mn.hivpos_agecat1634.rel*i
md.hivpos_agecat3554 <- mn.hivpos_agecat3554.rel*i
md.hivpos_agecat55 <- ((i - ((md.hivneg_agecat15*hiv_age_b3[1]) + 
                             (md.hivneg_agecat1634*hiv_age_b3[2]) + 
                             (md.hivneg_agecat3554*hiv_age_b3[3]) +
                             (md.hivneg_agecat55*hiv_age_b3[4]) +
                             (md.hivpos_agecat15*hiv_age_b3[5]) +
                             (md.hivpos_agecat1634*hiv_age_b3[6]) +
                             (md.hivpos_agecat3554*hiv_age_b3[7]))) / 
                             (1 - sum(hiv_age_b3[1:7])))

assign(paste0("edges.hiv_age0_b3.md", i), md.hivneg_agecat15 * sum(hiv_age_b3 == 0))
assign(paste0("edges.hiv_age1_b3.md", i), md.hivneg_agecat1634 * sum(hiv_age_b3 == 1))
assign(paste0("edges.hiv_age2_b3.md", i), md.hivneg_agecat3554 * sum(hiv_age_b3 == 2))
assign(paste0("edges.hiv_age3_b3.md", i), md.hivneg_agecat55 * sum(hiv_age_b3 == 3))
assign(paste0("edges.hiv_age4_b3.md", i), md.hivpos_agecat15 * sum(hiv_age_b3 == 4))
assign(paste0("edges.hiv_age5_b3.md", i), md.hivpos_agecat1634 * sum(hiv_age_b3 == 5))
assign(paste0("edges.hiv_age6_b3.md", i), md.hivpos_agecat3554 * sum(hiv_age_b3 == 6))
assign(paste0("edges.hiv_age7_b3.md", i), md.hivpos_agecat55 * sum(hiv_age_b3 == 7))
  
hivage_nfstats <- numeric(8)
hivage_nfstats[1] <- md.hivneg_agecat15 * sum(hiv_age_b3== 0)
hivage_nfstats[2] <- md.hivneg_agecat1634 * sum(hiv_age_b3== 1)
hivage_nfstats[3] <- md.hivneg_agecat3554 * sum(hiv_age_b3== 2)
hivage_nfstats[4] <- md.hivneg_agecat55 * sum(hiv_age_b3== 3)
hivage_nfstats[5] <- md.hivpos_agecat15 * sum(hiv_age_b3== 4)
hivage_nfstats[6] <- md.hivpos_agecat1634 * sum(hiv_age_b3== 5)
hivage_nfstats[7] <- md.hivpos_agecat3554 * sum(hiv_age_b3== 6)
hivage_nfstats[8] <- md.hivpos_agecat55 * sum(hiv_age_b3 == 7)
  
hivage_nfstats_all_b3[[i]] <- hivage_nfstats
}

hivage_nfstats_all_b4 <- list()

for(i in(1:20)){
  
md.hivneg_agecat15 <- mn.hivneg_agecat15.rel*i
md.hivneg_agecat1634 <- mn.hivneg_agecat1634.rel*i
md.hivneg_agecat3554 <- mn.hivneg_agecat3554.rel*i
md.hivneg_agecat55 <- mn.hivneg_agecat55.rel*i
md.hivpos_agecat15 <- mn.hivpos_agecat15.rel*i
md.hivpos_agecat1634 <- mn.hivpos_agecat1634.rel*i
md.hivpos_agecat3554 <- mn.hivpos_agecat3554.rel*i
md.hivpos_agecat55 <- ((i - ((md.hivneg_agecat15*hiv_age_b4[1]) + 
                             (md.hivneg_agecat1634*hiv_age_b4[2]) + 
                             (md.hivneg_agecat3554*hiv_age_b4[3]) +
                             (md.hivneg_agecat55*hiv_age_b4[4]) +
                             (md.hivpos_agecat15*hiv_age_b4[5]) +
                             (md.hivpos_agecat1634*hiv_age_b4[6]) +
                             (md.hivpos_agecat3554*hiv_age_b4[7]))) / 
                             (1 - sum(hiv_age_b4[1:7])))

assign(paste0("edges.hiv_age0_b4.md", i), md.hivneg_agecat15 * sum(hiv_age_b4 == 0))
assign(paste0("edges.hiv_age1_b4.md", i), md.hivneg_agecat1634 * sum(hiv_age_b4 == 1))
assign(paste0("edges.hiv_age2_b4.md", i), md.hivneg_agecat3554 * sum(hiv_age_b4 == 2))
assign(paste0("edges.hiv_age3_b4.md", i), md.hivneg_agecat55 * sum(hiv_age_b4 == 3))
assign(paste0("edges.hiv_age4_b4.md", i), md.hivpos_agecat15 * sum(hiv_age_b4 == 4))
assign(paste0("edges.hiv_age5_b4.md", i), md.hivpos_agecat1634 * sum(hiv_age_b4 == 5))
assign(paste0("edges.hiv_age6_b4.md", i), md.hivpos_agecat3554 * sum(hiv_age_b4 == 6))
assign(paste0("edges.hiv_age7_b4.md", i), md.hivpos_agecat55 * sum(hiv_age_b4 == 7))
  
hivage_nfstats <- numeric(8)
hivage_nfstats[1] <- md.hivneg_agecat15 * sum(hiv_age_b4== 0)
hivage_nfstats[2] <- md.hivneg_agecat1634 * sum(hiv_age_b4== 1)
hivage_nfstats[3] <- md.hivneg_agecat3554 * sum(hiv_age_b4== 2)
hivage_nfstats[4] <- md.hivneg_agecat55 * sum(hiv_age_b4== 3)
hivage_nfstats[5] <- md.hivpos_agecat15 * sum(hiv_age_b4== 4)
hivage_nfstats[6] <- md.hivpos_agecat1634 * sum(hiv_age_b4== 5)
hivage_nfstats[7] <- md.hivpos_agecat3554 * sum(hiv_age_b4== 6)
hivage_nfstats[8] <- md.hivpos_agecat55 * sum(hiv_age_b4 == 7)
  
hivage_nfstats_all_b4[[i]] <- hivage_nfstats
}

##sm_age_c1/c2/c3/c4
smage_nfstats_all_c1 <- list()

for(i in(1:20)){
  
md.smneg_agecat15 <- mn.smneg_agecat15.rel*i
md.smneg_agecat1634 <- mn.smneg_agecat1634.rel*i
md.smneg_agecat3554 <- mn.smneg_agecat3554.rel*i
md.smneg_agecat55 <- mn.smneg_agecat55.rel*i
md.smpos_agecat15 <- mn.smpos_agecat15.rel*i
md.smpos_agecat1634 <- mn.smpos_agecat1634.rel*i
md.smpos_agecat3554 <- mn.smpos_agecat3554.rel*i
md.smpos_agecat55 <- ((i - ((md.smneg_agecat15*sm_age_c1[1]) + 
                             (md.smneg_agecat1634*sm_age_c1[2]) + 
                             (md.smneg_agecat3554*sm_age_c1[3]) +
                             (md.smneg_agecat55*sm_age_c1[4]) +
                             (md.smpos_agecat15*sm_age_c1[5]) +
                             (md.smpos_agecat1634*sm_age_c1[6]) +
                             (md.smpos_agecat3554*sm_age_c1[7]))) / 
                             (1 - sum(sm_age_c1[1:7])))

assign(paste0("edges.sm_age0_c1.md", i), md.smneg_agecat15 * sum(sm_age_c1 == 0))
assign(paste0("edges.sm_age1_c1.md", i), md.smneg_agecat1634 * sum(sm_age_c1 == 1))
assign(paste0("edges.sm_age2_c1.md", i), md.smneg_agecat3554 * sum(sm_age_c1 == 2))
assign(paste0("edges.sm_age3_c1.md", i), md.smneg_agecat55 * sum(sm_age_c1 == 3))
assign(paste0("edges.sm_age4_c1.md", i), md.smpos_agecat15 * sum(sm_age_c1 == 4))
assign(paste0("edges.sm_age5_c1.md", i), md.smpos_agecat1634 * sum(sm_age_c1 == 5))
assign(paste0("edges.sm_age6_c1.md", i), md.smpos_agecat3554 * sum(sm_age_c1 == 6))
assign(paste0("edges.sm_age7_c1.md", i), md.smpos_agecat55 * sum(sm_age_c1 == 7))
  
smage_nfstats <- numeric(8)
smage_nfstats[1] <- md.smneg_agecat15 * sum(sm_age_c1== 0)
smage_nfstats[2] <- md.smneg_agecat1634 * sum(sm_age_c1== 1)
smage_nfstats[3] <- md.smneg_agecat3554 * sum(sm_age_c1== 2)
smage_nfstats[4] <- md.smneg_agecat55 * sum(sm_age_c1== 3)
smage_nfstats[5] <- md.smpos_agecat15 * sum(sm_age_c1== 4)
smage_nfstats[6] <- md.smpos_agecat1634 * sum(sm_age_c1== 5)
smage_nfstats[7] <- md.smpos_agecat3554 * sum(sm_age_c1== 6)
smage_nfstats[8] <- md.smpos_agecat55 * sum(sm_age_c1 == 7)
  
smage_nfstats_all_c1[[i]] <- smage_nfstats
}

smage_nfstats_all_c2 <- list()

for(i in(1:20)){
  
md.smneg_agecat15 <- mn.smneg_agecat15.rel*i
md.smneg_agecat1634 <- mn.smneg_agecat1634.rel*i
md.smneg_agecat3554 <- mn.smneg_agecat3554.rel*i
md.smneg_agecat55 <- mn.smneg_agecat55.rel*i
md.smpos_agecat15 <- mn.smpos_agecat15.rel*i
md.smpos_agecat1634 <- mn.smpos_agecat1634.rel*i
md.smpos_agecat3554 <- mn.smpos_agecat3554.rel*i
md.smpos_agecat55 <- ((i - ((md.smneg_agecat15*sm_age_c2[1]) + 
                             (md.smneg_agecat1634*sm_age_c2[2]) + 
                             (md.smneg_agecat3554*sm_age_c2[3]) +
                             (md.smneg_agecat55*sm_age_c2[4]) +
                             (md.smpos_agecat15*sm_age_c2[5]) +
                             (md.smpos_agecat1634*sm_age_c2[6]) +
                             (md.smpos_agecat3554*sm_age_c2[7]))) / 
                             (1 - sum(sm_age_c2[1:7])))

assign(paste0("edges.sm_age0_c2.md", i), md.smneg_agecat15 * sum(sm_age_c2 == 0))
assign(paste0("edges.sm_age1_c2.md", i), md.smneg_agecat1634 * sum(sm_age_c2 == 1))
assign(paste0("edges.sm_age2_c2.md", i), md.smneg_agecat3554 * sum(sm_age_c2 == 2))
assign(paste0("edges.sm_age3_c2.md", i), md.smneg_agecat55 * sum(sm_age_c2 == 3))
assign(paste0("edges.sm_age4_c2.md", i), md.smpos_agecat15 * sum(sm_age_c2 == 4))
assign(paste0("edges.sm_age5_c2.md", i), md.smpos_agecat1634 * sum(sm_age_c2 == 5))
assign(paste0("edges.sm_age6_c2.md", i), md.smpos_agecat3554 * sum(sm_age_c2 == 6))
assign(paste0("edges.sm_age7_c2.md", i), md.smpos_agecat55 * sum(sm_age_c2 == 7))
  
smage_nfstats <- numeric(8)
smage_nfstats[1] <- md.smneg_agecat15 * sum(sm_age_c2== 0)
smage_nfstats[2] <- md.smneg_agecat1634 * sum(sm_age_c2== 1)
smage_nfstats[3] <- md.smneg_agecat3554 * sum(sm_age_c2== 2)
smage_nfstats[4] <- md.smneg_agecat55 * sum(sm_age_c2== 3)
smage_nfstats[5] <- md.smpos_agecat15 * sum(sm_age_c2== 4)
smage_nfstats[6] <- md.smpos_agecat1634 * sum(sm_age_c2== 5)
smage_nfstats[7] <- md.smpos_agecat3554 * sum(sm_age_c2== 6)
smage_nfstats[8] <- md.smpos_agecat55 * sum(sm_age_c2 == 7)
  
smage_nfstats_all_c2[[i]] <- smage_nfstats
}

smage_nfstats_all_c3 <- list()

for(i in(1:20)){
  
md.smneg_agecat15 <- mn.smneg_agecat15.rel*i
md.smneg_agecat1634 <- mn.smneg_agecat1634.rel*i
md.smneg_agecat3554 <- mn.smneg_agecat3554.rel*i
md.smneg_agecat55 <- mn.smneg_agecat55.rel*i
md.smpos_agecat15 <- mn.smpos_agecat15.rel*i
md.smpos_agecat1634 <- mn.smpos_agecat1634.rel*i
md.smpos_agecat3554 <- mn.smpos_agecat3554.rel*i
md.smpos_agecat55 <- ((i - ((md.smneg_agecat15*sm_age_c3[1]) + 
                             (md.smneg_agecat1634*sm_age_c3[2]) + 
                             (md.smneg_agecat3554*sm_age_c3[3]) +
                             (md.smneg_agecat55*sm_age_c3[4]) +
                             (md.smpos_agecat15*sm_age_c3[5]) +
                             (md.smpos_agecat1634*sm_age_c3[6]) +
                             (md.smpos_agecat3554*sm_age_c3[7]))) / 
                             (1 - sum(sm_age_c3[1:7])))

assign(paste0("edges.sm_age0_c3.md", i), md.smneg_agecat15 * sum(sm_age_c3 == 0))
assign(paste0("edges.sm_age1_c3.md", i), md.smneg_agecat1634 * sum(sm_age_c3 == 1))
assign(paste0("edges.sm_age2_c3.md", i), md.smneg_agecat3554 * sum(sm_age_c3 == 2))
assign(paste0("edges.sm_age3_c3.md", i), md.smneg_agecat55 * sum(sm_age_c3 == 3))
assign(paste0("edges.sm_age4_c3.md", i), md.smpos_agecat15 * sum(sm_age_c3 == 4))
assign(paste0("edges.sm_age5_c3.md", i), md.smpos_agecat1634 * sum(sm_age_c3 == 5))
assign(paste0("edges.sm_age6_c3.md", i), md.smpos_agecat3554 * sum(sm_age_c3 == 6))
assign(paste0("edges.sm_age7_c3.md", i), md.smpos_agecat55 * sum(sm_age_c3 == 7))
  
smage_nfstats <- numeric(8)
smage_nfstats[1] <- md.smneg_agecat15 * sum(sm_age_c3== 0)
smage_nfstats[2] <- md.smneg_agecat1634 * sum(sm_age_c3== 1)
smage_nfstats[3] <- md.smneg_agecat3554 * sum(sm_age_c3== 2)
smage_nfstats[4] <- md.smneg_agecat55 * sum(sm_age_c3== 3)
smage_nfstats[5] <- md.smpos_agecat15 * sum(sm_age_c3== 4)
smage_nfstats[6] <- md.smpos_agecat1634 * sum(sm_age_c3== 5)
smage_nfstats[7] <- md.smpos_agecat3554 * sum(sm_age_c3== 6)
smage_nfstats[8] <- md.smpos_agecat55 * sum(sm_age_c3 == 7)
  
smage_nfstats_all_c3[[i]] <- smage_nfstats
}

smage_nfstats_all_c4 <- list()

for(i in(1:20)){
  
md.smneg_agecat15 <- mn.smneg_agecat15.rel*i
md.smneg_agecat1634 <- mn.smneg_agecat1634.rel*i
md.smneg_agecat3554 <- mn.smneg_agecat3554.rel*i
md.smneg_agecat55 <- mn.smneg_agecat55.rel*i
md.smpos_agecat15 <- mn.smpos_agecat15.rel*i
md.smpos_agecat1634 <- mn.smpos_agecat1634.rel*i
md.smpos_agecat3554 <- mn.smpos_agecat3554.rel*i
md.smpos_agecat55 <- ((i - ((md.smneg_agecat15*sm_age_c4[1]) + 
                             (md.smneg_agecat1634*sm_age_c4[2]) + 
                             (md.smneg_agecat3554*sm_age_c4[3]) +
                             (md.smneg_agecat55*sm_age_c4[4]) +
                             (md.smpos_agecat15*sm_age_c4[5]) +
                             (md.smpos_agecat1634*sm_age_c4[6]) +
                             (md.smpos_agecat3554*sm_age_c4[7]))) / 
                             (1 - sum(sm_age_c4[1:7])))

assign(paste0("edges.sm_age0_c4.md", i), md.smneg_agecat15 * sum(sm_age_c4 == 0))
assign(paste0("edges.sm_age1_c4.md", i), md.smneg_agecat1634 * sum(sm_age_c4 == 1))
assign(paste0("edges.sm_age2_c4.md", i), md.smneg_agecat3554 * sum(sm_age_c4 == 2))
assign(paste0("edges.sm_age3_c4.md", i), md.smneg_agecat55 * sum(sm_age_c4 == 3))
assign(paste0("edges.sm_age4_c4.md", i), md.smpos_agecat15 * sum(sm_age_c4 == 4))
assign(paste0("edges.sm_age5_c4.md", i), md.smpos_agecat1634 * sum(sm_age_c4 == 5))
assign(paste0("edges.sm_age6_c4.md", i), md.smpos_agecat3554 * sum(sm_age_c4 == 6))
assign(paste0("edges.sm_age7_c4.md", i), md.smpos_agecat55 * sum(sm_age_c4 == 7))
  
smage_nfstats <- numeric(8)
smage_nfstats[1] <- md.smneg_agecat15 * sum(sm_age_c4== 0)
smage_nfstats[2] <- md.smneg_agecat1634 * sum(sm_age_c4== 1)
smage_nfstats[3] <- md.smneg_agecat3554 * sum(sm_age_c4== 2)
smage_nfstats[4] <- md.smneg_agecat55 * sum(sm_age_c4== 3)
smage_nfstats[5] <- md.smpos_agecat15 * sum(sm_age_c4== 4)
smage_nfstats[6] <- md.smpos_agecat1634 * sum(sm_age_c4== 5)
smage_nfstats[7] <- md.smpos_agecat3554 * sum(sm_age_c4== 6)
smage_nfstats[8] <- md.smpos_agecat55 * sum(sm_age_c4 == 7)
  
smage_nfstats_all_c4[[i]] <- smage_nfstats
}


#combine all vars into a dataframe
#columns are cough categories (0-5), rows are mean degrees. 
#e.g. for md2 models, want cough_nfstats_mat[x,1] where x is cough category
smage_nfstats_c1_mat <- matrix(unlist(smage_nfstats_all_c1), nrow=20, ncol=8, byrow=TRUE)
smage_nfstats_c2_mat <- matrix(unlist(smage_nfstats_all_c2), nrow=20, ncol=8, byrow=TRUE)
smage_nfstats_c3_mat <- matrix(unlist(smage_nfstats_all_c3), nrow=20, ncol=8, byrow=TRUE)
smage_nfstats_c4_mat <- matrix(unlist(smage_nfstats_all_c4), nrow=20, ncol=8, byrow=TRUE)

hivage_nfstats_b1_mat <- matrix(unlist(hivage_nfstats_all_b1), nrow=20, ncol=8, byrow=TRUE)
hivage_nfstats_b2_mat <- matrix(unlist(hivage_nfstats_all_b2), nrow=20, ncol=8, byrow=TRUE)
hivage_nfstats_b3_mat <- matrix(unlist(hivage_nfstats_all_b3), nrow=20, ncol=8, byrow=TRUE)
hivage_nfstats_b4_mat <- matrix(unlist(hivage_nfstats_all_b4), nrow=20, ncol=8, byrow=TRUE)

```

```{r, sample from networks with changed attribute distributions}

##############################################
#ERGMs USING NEW ATTRIBUTE DIST'NS OF HIV/SMEAR STATUS
##############################################

nw_b1 <- list()

for(i in c(2, 5, 8, 10, 15, 20)){

  
nw <- ergm(nw_sim_un_b1 ~ edges + nodefactor("hp", base = 1) + nodefactor("yr", base = 1) + nodefactor("cough", base = 5:6) + nodefactor("smstat_age", base = c(1, 4:5, 8)) + nodefactor("hiv_age_b1", base = c(1:5, 8)), control = control.ergm(MCMC.burnin = 100000, MCMC.samplesize=10000, MCMLE.maxit = 100, MCMC.interval = 5000, MCMLE.density.guard = exp(10)),
                                    target.stats = c(edges_nfstats[i,2], 
                                          hp_nfstats_mat[i,1], 
                                          yr_nfstats_mat[i,2], yr_nfstats_mat[i,3], yr_nfstats_mat[i,4],
                                          cough_nfstats_mat[i,1], cough_nfstats_mat[i,2], cough_nfstats_mat[i,3], cough_nfstats_mat[i,4], 
                                          smage_nfstats_mat[i,2], smage_nfstats_mat[i,3], smage_nfstats_mat[i,6], smage_nfstats_mat[i,7],
                                          hivage_nfstats_b1_mat[i,6], hivage_nfstats_b1_mat[i,7]))

nw_b1[[i]]<- nw

saveRDS(nw_b1, file = paste("nw", n_sim, "md", i, "b1.RDS", sep = "_"))

}

#...repeat for b2-b4 

nw_c1 <- list()

for(i in c(2, 5, 8, 10, 15, 20)){

  
nw <- ergm(nw_sim_un_c1 ~ edges + nodefactor("hp", base = 1) + nodefactor("yr", base = 1) + nodefactor("cough", base = 5:6) + nodefactor("smstat_age_c1", base = c(1, 4:5, 8)) + nodefactor("hiv_age", base = c(1:5, 8)), control = control.ergm(MCMC.burnin = 100000, MCMC.samplesize=10000, MCMLE.maxit = 100, MCMC.interval = 5000, MCMLE.density.guard = exp(10)),
                                    target.stats = c(edges_nfstats[i,2], 
                                          hp_nfstats_mat[i,1], 
                                          yr_nfstats_mat[i,2], yr_nfstats_mat[i,3], yr_nfstats_mat[i,4],
                                          cough_nfstats_mat[i,1], cough_nfstats_mat[i,2], cough_nfstats_mat[i,3], cough_nfstats_mat[i,4], 
                                          smage_nfstats_c1_mat[i,2], smage_nfstats_c1_mat[i,3], smage_nfstats_c1_mat[i,6], smage_nfstats_c1_mat[i,7],
                                          hivage_nfstats_mat[i,6], hivage_nfstats_mat[i,7]))

nw_c1[[i]]<- nw

saveRDS(nw_c1, file = paste("nw", n_sim, "md", i, "c1.RDS", sep = "_"))

}

#...repeat for c2-c4 
 
#sample from networks with changed attribute distributions
for(k in(c(2, 5, 8, 10, 15, 20))){
  
        degdist <- list()
      
        med <- list()
        
for(i in 1:nsamples){
    
      nw_sim <- simulate(nw_b1[[k]], nsim = 1, monitor = ~ degree(0:100) + meandeg)
    
      sim_deg <- degree(get.inducedSubgraph(nw_sim, ransamp), gmode = "graph" , cmode="freeman", ignore.eval = TRUE)
      
      simdegdist <- table(sim_deg) 
      
      degdist[[i]] <- as.data.frame(simdegdist)
      
      quantiles <- quantile(sim_deg, c(0.25, 0.50, 0.75, 1)) #gives median degree and IQR for each network
      
      med[[i]] <- as.vector(quantiles)
      
      #delete simulated nw
      rm(nw_sim)

      } 
  
      saveRDS(degdist, file = paste("nw", n_sim, "sim", nsamples, "md", k, "b1_degdist.RDS", sep = "_"))
      saveRDS(med, file = paste("nw", n_sim, "sim", nsamples, "md", k, "b1_med.RDS", sep = "_"))
}

#repeat for b2-b4, c1-c4
```

```{r, adding latent factor}

##############################################
#ADDING LATENT FACTOR RELATED TO TRANSMISSION
##############################################

lf_in10 <- rbinom(n_sim, 1, 0.10) 
lf_in20 <- rbinom(n_sim, 1, 0.20) 
lf_in30 <- rbinom(n_sim, 1, 0.30) 
lf_in40 <- rbinom(n_sim, 1, 0.40) 

#assign latent factor to nodes in network
nw_sim_un <- set.vertex.attribute(nw_sim_un, "lf_10", lf_in10)
nw_sim_un <- set.vertex.attribute(nw_sim_un, "lf_20", lf_in20)
nw_sim_un <- set.vertex.attribute(nw_sim_un, "lf_30", lf_in30)
nw_sim_un <- set.vertex.attribute(nw_sim_un, "lf_40", lf_in40)

#vary strength of latent factor
mn.lf_10 <- 10 #lf10 means cases with factor have mean 10 links, cases without factor have mean 1
mn.nonlf_10 <- 1
mn.lf_20 <- 20 
mn.nonlf_20 <- 1
mn.lf_40 <- 40  #lf40 means cases with factor have mean 40 links, cases without factor have mean 1
mn.nonlf_40 <- 1

#calculate target statistics for network (number of mean edges for nodes with lf attribute)
mn.lf_10.rel <- mn.lf_10/md.trax.le5 
mn.nonlf_10.rel <- mn.nonlf_10/md.trax.le5

mn.lf_20.rel <- mn.lf_20/md.trax.le5
mn.nonlf_20.rel <- mn.nonlf_20/md.trax.le5

mn.lf_40.rel <- mn.lf_40/md.trax.le5
mn.nonlf_40.rel <- mn.nonlf_40/md.trax.le5

#calculate target stats at different *prevalences* of latent factor among network nodes/cases
###Prevalence of lf in network = 0.10
#lf10 (strength of latent factor is x10)
lf_10_nfstats_in10_all <- list()

for(i in(1:20)){
  
md.lf_10 <- mn.lf_10.rel*i
md.nonlf_10 <- (i - (md.lf_10 * 0.10))/(1-0.10)

assign((paste0("edges.lf_10.md", i)), (md.lf_10 * sum(lf_in10 == 1)))
assign(paste0("edges.nonlf_10.md", i), md.nonlf_10 * sum(lf_in10 == 0))

lf_10_nfstats <- numeric(2)
lf_10_nfstats[1] <- md.lf_10 * sum(lf_in10 == 1)
lf_10_nfstats[2] <- md.nonlf_10 * sum(lf_in10 == 0)

lf_10_nfstats_in10_all[[i]] <- lf_10_nfstats
}

#lf20 (strength of latent factor is x20)
lf_20_nfstats_in10_all <- list()

for(i in(1:20)){
  
md.lf_20 <- mn.lf_20.rel*i
md.nonlf_20 <- (i - (md.lf_20 * 0.10))/(1-0.10)

assign((paste0("edges.lf_20.md", i)), (md.lf_20 * sum(lf_in10 == 1)))
assign(paste0("edges.nonlf_20.md", i), md.nonlf_20 * sum(lf_in10 == 0))

lf_20_nfstats <- numeric(2)
lf_20_nfstats[1] <- md.lf_20 * sum(lf_in10 == 1)
lf_20_nfstats[2] <- md.nonlf_20 * sum(lf_in10 == 0)

lf_20_nfstats_in10_all[[i]] <- lf_20_nfstats
}

#lf40 (strength of latent factor is x40)
lf_40_nfstats_in10_all <- list()

for(i in(1:20)){
  
md.lf_40 <- mn.lf_40.rel*i
md.nonlf_40 <- (i - (md.lf_40 * 0.10))/(1-0.10)

assign((paste0("edges.lf_40.md", i)), (md.lf_40 * sum(lf_in10 == 1)))
assign(paste0("edges.nonlf_40.md", i), md.nonlf_40 * sum(lf_in10 == 0))

lf_40_nfstats <- numeric(2)
lf_40_nfstats[1] <- md.lf_40 * sum(lf_in10 == 1)
lf_40_nfstats[2] <- md.nonlf_40 * sum(lf_in10 == 0)

lf_40_nfstats_in10_all[[i]] <- lf_40_nfstats
}

#...not shown: 20%, 30% prevalence

###Prevalence = 0.40
#lf10
lf_10_nfstats_in40_all <- list()

for(i in(1:20)){
  
md.lf_10 <- mn.lf_10.rel*i
md.nonlf_10 <- (i - (md.lf_10 * 0.40))/(1-0.40)

assign((paste0("edges.lf_10.md", i)), (md.lf_10 * sum(lf_in40 == 1)))
assign(paste0("edges.nonlf_10.md", i), md.nonlf_10 * sum(lf_in40 == 0))

lf_10_nfstats <- numeric(2)
lf_10_nfstats[1] <- md.lf_10 * sum(lf_in40 == 1)
lf_10_nfstats[2] <- md.nonlf_10 * sum(lf_in40 == 0)

lf_10_nfstats_in40_all[[i]] <- lf_10_nfstats
}

#lf20
lf_20_nfstats_in40_all <- list()

for(i in(1:20)){
  
md.lf_20 <- mn.lf_20.rel*i
md.nonlf_20 <- (i - (md.lf_20 * 0.40))/(1-0.40)

assign((paste0("edges.lf_20.md", i)), (md.lf_20 * sum(lf_in40 == 1)))
assign(paste0("edges.nonlf_20.md", i), md.nonlf_20 * sum(lf_in40 == 0))

lf_20_nfstats <- numeric(2)
lf_20_nfstats[1] <- md.lf_20 * sum(lf_in40 == 1)
lf_20_nfstats[2] <- md.nonlf_20 * sum(lf_in40 == 0)

lf_20_nfstats_in40_all[[i]] <- lf_20_nfstats
}

#lf40
lf_40_nfstats_in40_all <- list()

for(i in(1:20)){
  
md.lf_40 <- mn.lf_40.rel*i
md.nonlf_40 <- (i - (md.lf_40 * 0.40))/(1-0.40)

assign((paste0("edges.lf_40.md", i)), (md.lf_40 * sum(lf_in40 == 1)))
assign(paste0("edges.nonlf_40.md", i), md.nonlf_40 * sum(lf_in40 == 0))

lf_40_nfstats <- numeric(2)
lf_40_nfstats[1] <- md.lf_40 * sum(lf_in40 == 1)
lf_40_nfstats[2] <- md.nonlf_40 * sum(lf_in40 == 0)

lf_40_nfstats_in40_all[[i]] <- lf_40_nfstats
}

#combine into matrices
#columns are cough categories (0-5), rows are mean degrees. 
#e.g. for md2 models, want cough_nfstats_mat[x,1] where x is cough category

lf_10_nfstats_in10_mat <- matrix(unlist(lf_10_nfstats_in10_all), nrow=20, ncol=2, byrow=TRUE)
lf_10_nfstats_in20_mat <- matrix(unlist(lf_10_nfstats_in20_all), nrow=20, ncol=2, byrow=TRUE)
lf_10_nfstats_in30_mat <- matrix(unlist(lf_10_nfstats_in30_all), nrow=20, ncol=2, byrow=TRUE)
lf_10_nfstats_in40_mat <- matrix(unlist(lf_10_nfstats_in40_all), nrow=20, ncol=2, byrow=TRUE)

#...not shown: 20%, 30% prevalence

lf_40_nfstats_in10_mat <- matrix(unlist(lf_40_nfstats_in10_all), nrow=20, ncol=2, byrow=TRUE)
lf_40_nfstats_in20_mat <- matrix(unlist(lf_40_nfstats_in20_all), nrow=20, ncol=2, byrow=TRUE)
lf_40_nfstats_in30_mat <- matrix(unlist(lf_40_nfstats_in30_all), nrow=20, ncol=2, byrow=TRUE)
lf_40_nfstats_in40_mat <- matrix(unlist(lf_40_nfstats_in40_all), nrow=20, ncol=2, byrow=TRUE)

```

```{r, run lf models}

##############################################
#ERGMs for MODELS WITH LATENT FACTOR RELATED TO TRANSMISSION
##############################################

#Prevalence = 0.10 (lf10, 20, 40)
nw_lf_10in10 <- list()

for(i in c(2, 5, 8, 10, 15, 20)){

  
nw <- ergm(nw_sim_un ~ edges + nodefactor("hp", base = 1) + nodefactor("yr", base = 1) + nodefactor("cough", base = 5:6) + nodefactor("smstat_age", base = c(1, 4:5, 8)) + nodefactor("hiv_age", base = c(1:5, 8)) + nodefactor("lf_10"), control = control.ergm(MCMC.burnin = 100000, MCMC.samplesize=10000, MCMLE.maxit = 100, MCMC.interval = 5000, MCMLE.density.guard = exp(10)),
                                    target.stats = c(edges_nfstats[i,2], 
                                          hp_nfstats_mat[i,1], 
                                          yr_nfstats_mat[i,2], yr_nfstats_mat[i,3], yr_nfstats_mat[i,4],
                                          cough_nfstats_mat[i,1], cough_nfstats_mat[i,2], cough_nfstats_mat[i,3], cough_nfstats_mat[i,4], 
                                          smage_nfstats_mat[i,2], smage_nfstats_mat[i,3], smage_nfstats_mat[i,6], smage_nfstats_mat[i,7],
                                          hivage_nfstats_mat[i,6], hivage_nfstats_mat[i,7],
                                          lf_10_nfstats_in10_mat[i,1]))

nw_lf_10in10[[i]]<- nw

saveRDS(nw, file = paste("nw", n_sim, "md", i, "lf10in10.RDS", sep = "_"))

  }
  
nw_lf_20in10 <- list()

for(i in c(2, 5, 8, 10, 15, 20)){

  
nw <- ergm(nw_sim_un ~ edges + nodefactor("hp", base = 1) + nodefactor("yr", base = 1) + nodefactor("cough", base = 5:6) + nodefactor("smstat_age", base = c(1, 4:5, 8)) + nodefactor("hiv_age", base = c(1:5, 8)) + nodefactor("lf_10"), control = control.ergm(MCMC.burnin = 100000, MCMC.samplesize=10000, MCMLE.maxit = 100, MCMC.interval = 5000, MCMLE.density.guard = exp(10)),
                                    target.stats = c(edges_nfstats[i,2], 
                                          hp_nfstats_mat[i,1], 
                                          yr_nfstats_mat[i,2], yr_nfstats_mat[i,3], yr_nfstats_mat[i,4],
                                          cough_nfstats_mat[i,1], cough_nfstats_mat[i,2], cough_nfstats_mat[i,3], cough_nfstats_mat[i,4], 
                                          smage_nfstats_mat[i,2], smage_nfstats_mat[i,3], smage_nfstats_mat[i,6], smage_nfstats_mat[i,7],
                                          hivage_nfstats_mat[i,6], hivage_nfstats_mat[i,7],
                                          lf_20_nfstats_in10_mat[i,1]))

nw_lf_20in10[[i]]<- nw

saveRDS(nw, file = paste("nw", n_sim, "md", i, "lf20in10.RDS", sep = "_"))

}

nw_lf_40in10 <- list()

for(i in c(2, 5, 8, 10, 15, 20)){

  
nw <- ergm(nw_sim_un ~ edges + nodefactor("hp", base = 1) + nodefactor("yr", base = 1) + nodefactor("cough", base = 5:6) + nodefactor("smstat_age", base = c(1, 4:5, 8)) + nodefactor("hiv_age", base = c(1:5, 8)) + nodefactor("lf_10"), control = control.ergm(MCMC.burnin = 100000, MCMC.samplesize=10000, MCMLE.maxit = 100, MCMC.interval = 5000, MCMLE.density.guard = exp(10)),
                                    target.stats = c(edges_nfstats[i,2], 
                                          hp_nfstats_mat[i,1], 
                                          yr_nfstats_mat[i,2], yr_nfstats_mat[i,3], yr_nfstats_mat[i,4],
                                          cough_nfstats_mat[i,1], cough_nfstats_mat[i,2], cough_nfstats_mat[i,3], cough_nfstats_mat[i,4], 
                                          smage_nfstats_mat[i,2], smage_nfstats_mat[i,3], smage_nfstats_mat[i,6], smage_nfstats_mat[i,7],
                                          hivage_nfstats_mat[i,6], hivage_nfstats_mat[i,7],
                                          lf_40_nfstats_in10_mat[i,1]))

nw_lf_40in10[[i]]<- nw

saveRDS(nw, file = paste("nw", n_sim, "md", i, "lf40in10.RDS", sep = "_"))

  }

```

```{r, sample lf models - ran and nonran}

##############################################
#SAMPLE FROM SIMULATED, FULL NETWORKS WITH LF
##############################################

nw_lf_40in10 <- list()
nw_lf_40in10[[2]] <- readRDS("nw_2000_md_2_lf40in10.RDS")
nw_lf_40in10[[5]] <- readRDS("nw_2000_md_5_lf40in10.RDS")
nw_lf_40in10[[8]] <- readRDS("nw_2000_md_8_lf40in10.RDS")
nw_lf_40in10[[10]] <- readRDS("nw_2000_md_10_lf40in10.RDS")
nw_lf_40in10[[15]] <- readRDS("nw_2000_md_15_lf40in10.RDS")
nw_lf_40in10[[20]] <- readRDS("nw_2000_md_20_lf40in10.RDS")
nw_lf_40in10 

for(k in(c(2, 5, 8, 10, 15, 20))){
  
        degdist <- list()
      
        med <- list()
        
for(i in 1:nsamples){
    
      nw_sim <- simulate(nw_lf_40in10[[k]], nsim = 1, monitor = ~ degree(0:100) + meandeg)
    
      sim_deg <- degree(get.inducedSubgraph(nw_sim, ransamp), gmode = "graph" , cmode="freeman", ignore.eval = TRUE)
      
      simdegdist <- table(sim_deg) 
      
      degdist[[i]] <- as.data.frame(simdegdist)
      
      quantiles <- quantile(sim_deg, c(0.25, 0.50, 0.75, 1)) #gives median degree and IQR for each network
      
      med[[i]] <- as.vector(quantiles)
      
      #delete simulated nw
      rm(nw_sim)

      } 
  
      saveRDS(degdist, file = paste("nw", n_sim, "sim", nsamples, "md", k, "lf40in10_degdist.RDS", sep = "_"))
      saveRDS(med, file = paste("nw", n_sim, "sim", nsamples, "md", k, "lf40in10_med.RDS", sep = "_"))
}

```
